#!/usr/bin/env python3
"""Write lib/config/hairstyle_catalog.dart from the gate's verdicts.

    export_catalog.py verdicts.json [--engines kontext] [--ol1nllm /path/to/Ol1nLLM]

`verdicts.json` maps hairstyle id → {"verdict": …, "note": …}, where the
verdict is "accept" | "reject" | "retune" for every engine or a map engine →
verdict. Each app gets what was accepted on every engine it runs: Tsumiki runs
HAIR_ENGINE alone (`--engines`, re-export after switching it), Ol1nLLM picks
Kontext or SDXL by preset (`--ol1nllm-engines`). Blocks and shapes come from
candidates/hairstyles.json, so a retuned block is edited there and re-measured,
never patched in Dart.
"""

import argparse

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
TARGET = REPO / "lib" / "config" / "hairstyle_catalog.dart"


def dart_str(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def accepted(verdicts: dict, key: str, engines: list[str]) -> bool:
    v = verdicts.get(key, {}).get("verdict")
    if isinstance(v, dict):
        return all(v.get(e) == "accept" for e in engines)
    return v == "accept"


def accepted_colours(verdicts: dict, engines: list[str]) -> list[tuple[str, dict]]:
    """Colours are gated like styles, under "colour:<id>" keys in verdicts.json."""
    sys.path.insert(0, str(HERE.parents[1]))
    import haircolours

    return [(cid, c) for cid, c in haircolours.COLOURS.items()
            if accepted(verdicts, f"colour:{cid}", engines)]


def ol1nllm_catalog(styles: list[dict], repo: Path, colours: list[tuple[str, dict]]) -> None:
    """Same survivors for Ol1nLLM's Kadeřník, Czech labels."""
    target = repo / "lib" / "models" / "hairstyle_catalog.dart"
    sections = {"Cuts": "Střihy", "Bangs": "Ofiny", "Texture": "Textura", "Updos": "Účesy nahoru",
                "Short": "Krátké", "Medium": "Střední", "Long": "Dlouhé",
                "Braids": "Copánky"}
    lines = [
        "// GENERATED by MangaPrompts tgbot/tools/bench/export_catalog.py from the",
        "// bench verdicts (MangaPrompts/docs/hair-matrix.md). Do not edit by hand.",
        "",
        # HairShape a spol. potřebují jen účesy — s prázdnou gate by nepoužitý
        # import shodil `flutter analyze` v CI appky
        *(["import 'hair_mask.dart';"] if styles else []),
        "import 'hairstyle_preset.dart';",
        "",
        "const kHairstyles = <HairstylePreset>[",
    ]
    for c in styles:
        sh = c["shape"]
        label = c["cs"][:1].upper() + c["cs"][1:]
        lines += [
            "  HairstylePreset(",
            f"    id: {dart_str(c['id'])},",
            f"    label: {dart_str(label)},",
            f"    group: {'kHairGroupWomen' if c['group'] == 'Women' else 'kHairGroupMen'},",
            f"    section: {dart_str(sections[c['section']])},",
            "    block:",
            f"        {dart_str(c['block'])},",
            f"    shape: HairShape(length: HairLength.{sh['length']}, bangs: HairBangs.{sh['bangs']}, updo: {str(sh['updo']).lower()}),",
            "  ),",
        ]
    lines.append("];")
    lines += ["", "const kHairColours = <HairColourPreset>["]
    for cid, c in colours:
        lines += [
            "  HairColourPreset(",
            f"    id: {dart_str(cid)},",
            f"    label: {dart_str(c['cs'][:1].upper() + c['cs'][1:])},",
            f"    phrase: {dart_str(c['phrase'])},",
            "  ),",
        ]
    lines.append("];")
    target.write_text("\n".join(lines) + "\n")
    print(f"{target}: {len(styles)} hairstyles, {len(colours)} colours")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("verdicts")
    ap.add_argument("--engines", default="kontext", help="Tsumiki's HAIR_ENGINE")
    ap.add_argument("--ol1nllm", type=Path)
    ap.add_argument("--ol1nllm-engines", default="kontext,sdxl")
    args = ap.parse_args()
    verdicts = json.loads(Path(args.verdicts).read_text())
    cands = json.loads((HERE / "candidates" / "hairstyles.json").read_text())

    def split(s: str) -> list[str]:
        return [e.strip() for e in s.split(",") if e.strip()]

    if args.ol1nllm:
        engines = split(args.ol1nllm_engines)
        ol1nllm_catalog([c for c in cands if accepted(verdicts, c["id"], engines)], args.ol1nllm,
                        accepted_colours(verdicts, engines))
    engines = split(args.engines)
    styles = [c for c in cands if accepted(verdicts, c["id"], engines)]
    colours = accepted_colours(verdicts, engines)
    lines = [
        "// GENERATED by tgbot/tools/bench/export_catalog.py from the bench verdicts",
        "// (docs/hair-matrix.md). Do not edit by hand: change the candidate in",
        "// tgbot/tools/bench/candidates/hairstyles.json, re-measure, re-export.",
        "",
        "import 'hairstyles.dart';",
        "",
        "const kHairstyles = <Hairstyle>[",
    ]
    for c in styles:
        sh = c["shape"]
        lines += [
            "  Hairstyle(",
            f"    id: {dart_str(c['id'])},",
            f"    label: {dart_str(c['label'])},",
            f"    group: {'kHairGroupWomen' if c['group'] == 'Women' else 'kHairGroupMen'},",
            f"    section: {dart_str(c['section'])},",
            "    block:",
            f"        {dart_str(c['block'])},",
            f"    shape: HairShape(length: HairLength.{sh['length']}, bangs: HairBangs.{sh['bangs']}, updo: {str(sh['updo']).lower()}),",
            "  ),",
        ]
    lines.append("];")
    lines += ["", "const kHairColours = <HairColour>["]
    for cid, c in colours:
        lines += [
            "  HairColour(",
            f"    id: {dart_str(cid)},",
            f"    label: {dart_str(c['label'])},",
            f"    group: {dart_str(c['group'])},",
            "  ),",
        ]
    lines.append("];")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"{TARGET}: {len(styles)} of {len(cands)} candidates, {len(colours)} colours "
          f"({'+'.join(engines)})")


if __name__ == "__main__":
    main()
