// GENERATED by tgbot/tools/bench/export_catalog.py from the bench verdicts
// (docs/hair-matrix.md). Do not edit by hand: change the candidate in
// tgbot/tools/bench/candidates/hairstyles.json, re-measure, re-export.

import 'hairstyles.dart';

const kHairstyles = <Hairstyle>[
  Hairstyle(
    id: 'face-framing',
    label: 'Face-Framing Layers',
    group: kHairGroupWomen,
    section: 'Cuts',
    block:
        'face-framing layers, shorter layered pieces around the face blending into the lengths, soft and flattering',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: false),
  ),
  Hairstyle(
    id: 'box-braids',
    label: 'Box Braids',
    group: kHairGroupWomen,
    section: 'Braids',
    block:
        'long box braids, many small neat three-strand braids falling past the shoulders',
    shape: HairShape(length: HairLength.long, bangs: HairBangs.none, updo: false),
  ),
  Hairstyle(
    id: 'dutch-braids',
    label: 'Dutch Braids',
    group: kHairGroupWomen,
    section: 'Braids',
    block:
        'two dutch braids, tight raised braids running from the hairline back along both sides of the head',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: false),
  ),
  Hairstyle(
    id: 'crown-braid',
    label: 'Crown Braid',
    group: kHairGroupWomen,
    section: 'Braids',
    block:
        'crown braid, a thick braid wrapped around the head like a halo with all the hair up',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: true),
  ),
  Hairstyle(
    id: 'm-buzz',
    label: 'Buzz Cut',
    group: kHairGroupMen,
    section: 'Short',
    block:
        'buzz cut, hair clipped uniformly very short all over the head',
    shape: HairShape(length: HairLength.short, bangs: HairBangs.none, updo: false),
  ),
  Hairstyle(
    id: 'm-man-bun',
    label: 'Man Bun',
    group: kHairGroupMen,
    section: 'Updos',
    block:
        'man bun, long hair pulled back and tied into a bun at the back of the head',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: true),
  ),
  Hairstyle(
    id: 'm-top-knot',
    label: 'Top Knot (Undercut)',
    group: kHairGroupMen,
    section: 'Updos',
    block:
        'men\'s top knot, long hair on top tied into a knot on the crown with shaved undercut sides',
    shape: HairShape(length: HairLength.keep, bangs: HairBangs.none, updo: true),
  ),
  Hairstyle(
    id: 'm-spiky',
    label: 'Spiky Hair',
    group: kHairGroupMen,
    section: 'Short',
    block:
        'spiky hair, short hair styled straight up into sharp textured spikes all over the top',
    shape: HairShape(length: HairLength.short, bangs: HairBangs.none, updo: false),
  ),
  Hairstyle(
    id: 'm-cornrows',
    label: 'Cornrows',
    group: kHairGroupMen,
    section: 'Short',
    block:
        'cornrows, hair braided flat to the scalp in straight neat rows running back from the hairline',
    shape: HairShape(length: HairLength.short, bangs: HairBangs.none, updo: false),
  ),
];

const kHairColours = <HairColour>[
  HairColour(
    id: 'platinum-blonde',
    label: 'Platinum blonde',
    group: 'Blonde',
    swatch: 0xFFDAD7DF,
  ),
  HairColour(
    id: 'ash-blonde',
    label: 'Ash blonde',
    group: 'Blonde',
    swatch: 0xFFD4C4BB,
  ),
  HairColour(
    id: 'honey-blonde',
    label: 'Honey blonde',
    group: 'Blonde',
    swatch: 0xFFCD903B,
  ),
  HairColour(
    id: 'copper-red',
    label: 'Copper red',
    group: 'Red',
    swatch: 0xFF792E17,
  ),
  HairColour(
    id: 'fox-red',
    label: 'Fox red',
    group: 'Red',
    swatch: 0xFFC23D1C,
  ),
  HairColour(
    id: 'auburn',
    label: 'Auburn',
    group: 'Red',
    swatch: 0xFF642C1E,
  ),
  HairColour(
    id: 'burgundy',
    label: 'Burgundy',
    group: 'Red',
    swatch: 0xFF420D10,
  ),
  HairColour(
    id: 'honey-balayage',
    label: 'Honey balayage',
    group: 'Brown',
    swatch: 0xFF5B3F2D,
  ),
  HairColour(
    id: 'jet-black',
    label: 'Jet black',
    group: 'Black & grey',
    swatch: 0xFF0A0807,
  ),
  HairColour(
    id: 'blue-black',
    label: 'Blue black',
    group: 'Black & grey',
    swatch: 0xFF152546,
  ),
  HairColour(
    id: 'silver-grey',
    label: 'Silver grey',
    group: 'Black & grey',
    swatch: 0xFFA6A3A8,
  ),
  HairColour(
    id: 'pastel-pink',
    label: 'Pastel pink',
    group: 'Fashion',
    swatch: 0xFFE67F9C,
  ),
  HairColour(
    id: 'hot-pink',
    label: 'Hot pink',
    group: 'Fashion',
    swatch: 0xFFC52F6D,
  ),
  HairColour(
    id: 'lavender',
    label: 'Lavender',
    group: 'Fashion',
    swatch: 0xFFA079BE,
  ),
  HairColour(
    id: 'electric-blue',
    label: 'Electric blue',
    group: 'Fashion',
    swatch: 0xFF1641C1,
  ),
  HairColour(
    id: 'teal',
    label: 'Mermaid teal',
    group: 'Fashion',
    swatch: 0xFF318280,
  ),
];
