// GENERATED by tgbot/tools/bench/export_catalog.py from the bench verdicts
// (docs/hair-matrix.md). Do not edit by hand: change the candidate in
// tgbot/tools/bench/candidates/hairstyles.json, re-measure, re-export.

import 'hairstyles.dart';

const kHairstyles = <Hairstyle>[
];

const kHairColours = <HairColour>[
];
